Deepend.DeependAncestry.Web/Models/SearchFormModel.cs
using System.ComponentModel.DataAnnotations;

namespace Deepend.DeependAncestry.Web.Models
{
    public class SearchFormModel
    {
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }

        [Display(Name = "Male")]
        public bool M { get; set; }

        [Display(Name = "Female")]
        public bool F { get; set; }
        public string Direction { get; set; }
    }
}

Deepend.DeependAncestry.Web/Controllers/AdvancedController.cs
using Deepend.DeependAncestry.Business.Services;
using Deepend.DeependAncestry.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Deepend.DeependAncestry.Web.Controllers
{
    public class AdvancedController : Controller
    {
        // GET: Advanced
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public PartialViewResult GetSearchResults(SearchFormModel model)
        {
            AncestryDataService ads = new AncestryDataService();

            return PartialView("_ResultsTable", ads.GetAdvancedSearchResults(model.name.ToLower(), model.M && model.F ? "M" : model.M ? "M" : model.F ? "F" : "M", model.Direction)); // default Male

        }

    }
}

Deepend.DeependAncestry.Web/Controllers/HomeController.cs
using Deepend.DeependAncestry.Business.Services;
using Deepend.DeependAncestry.Web.Models;
using System.Web.Mvc;

namespace Deepend.DeependAncestry.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult GetSearchResults(SearchFormModel model, int pageNumber)
        {
            AncestryDataService ads = new AncestryDataService();

            return PartialView("_ResultsTable", ads.GetSearchResults(model.name.ToLower(), model.M && model.F ? string.Empty : model.M ? "M" : model.F ? "F" : string.Empty, pageNumber));
        }

    }
}

Deepend.DeependAncestry.Web/Views/Advanced/Index.cshtml
@{
    ViewBag.Title = "Advanced Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <!-- Search Form -->
    @Html.Partial("_AdvancedSearchForm", new Deepend.DeependAncestry.Web.Models.SearchFormModel())
</div>

<div class="row" id="search-results">
    <!-- Results Table -->

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        $("#btnSearch").click(function (evt) {
            evt.preventDefault();
            $("#btnSearch").html("Searching...");
            $("#btnSearch").attr('disabled', 'disabled');
           // $("#name").attr('disabled', 'disabled');

            $("#search-results").html('');

            var form = $('#SearchForm');
            if (form.valid()) {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetSearchResults", "Advanced")",
                    data: form.serialize(),
                    success: function (response) {
                        $("#search-results").html(response);
                        $("#btnSearch").html("Search");
                        $("#btnSearch").removeAttr("disabled");
                       // $("#name").removeAttr("disabled");
                    },
                    error: function (errorData) {
                        $("#btnSearch").removeAttr("disabled");
                      //  $("#name").removeAttr("disabled");
                    }
                });
            }
        });

    </script>
}

Deepend.DeependAncestry.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Search Page";
}

<div class="row">
    <!-- Search Form -->
    @Html.Partial("_SearchForm", new Deepend.DeependAncestry.Web.Models.SearchFormModel())
</div>

<div class="row" id="search-results">
    <!-- Results Table -->

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnSearch").click(function (evt) {
                evt.preventDefault();
                $("#btnSearch").html("Searching...");

                $("#search-results").html('');

                var form = $('#SearchForm');
                if (form.valid()) {
                    $.ajax({
                        type: "GET",
                        url: "@Url.Action("GetSearchResults", "Home")",
                        data: form.serialize() + "&pageNumber=0",
                        success: function (response) {
                            $("#search-results").html(response);

                            $("#btnSearch").html("Search");

                            $(".changepage").click(function (evt) {
                                evt.preventDefault();
                                var pageNumber = $(this).data("pagenumber");

                                movePage(pageNumber);
                            });

                        },
                        error: function (errorData) {

                        }
                    });
                }
            });

        })

        function movePage(pageNumber) {
            var overlay = $('<div id="overlay"> Loading Page...  </div>');
            overlay.appendTo($("#search-results"))


            var form = $('#SearchForm');
            if (form.valid()) {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("GetSearchResults", "Home")",
                    data: form.serialize() + "&pageNumber=" + pageNumber,
                    success: function (response) {
                        $("#search-results").html(response);

                        $("#btnSearch").html("Search");

                        $(".changepage").click(function (evt) {
                            evt.preventDefault();
                            var pageNumber = $(this).data("pagenumber");
                            movePage(pageNumber);
                        });

                    },
                    error: function (errorData) {
                    }
                });
            }
        }



    </script>
}

Deepend.DeependAncestry.Web/Views/Shared/_AdvancedSearchForm.cshtml
@model Deepend.DeependAncestry.Web.Models.SearchFormModel

<form name="SearchForm" id="SearchForm" class="form-inline">
    <div class="col-md-7">
        <div class="col-md-12">
            @Html.TextBoxFor(model => model.name, new { placeholder = "Name", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.name)
        </div>
        <div class="col-md-12">
            <label>Gender: </label>
            <label class="checkbox-inline">
                @Html.CheckBoxFor(model => model.M) Male
            </label>
            <label class="checkbox-inline">
                @Html.CheckBoxFor(model => model.F) Female
            </label>
        </div>
        <div class="col-md-12">
            <label>Direction: </label>
            <label class="checkbox-inline">
                @Html.RadioButtonFor(model => model.Direction, "Ancestors") Ancestors
            </label>
            <label class="checkbox-inline">
                @Html.RadioButtonFor(model => model.Direction, "Descendants") Descendants
            </label>
        </div>
    </div>
    <div class="col-md-5 text-center">
        <button id="btnSearch" type="submit" class="btn btn-primary" style="width: 100%;">Search</button>
        @Html.ActionLink("Basic Search", "Index", "Home", null, new { @class = "advanced-search" })
    </div>

</form>

Deepend.DeependAncestry.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DeepAncestry - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                <h1>Deepend<strong>Ancestry</strong></h1>
            </div>
        </div>

        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Deepend.DeependAncestry.Web/Views/Shared/_ResultsTable.cshtml
@model Deepend.DeependAncestry.Data.Models.AncestryDataPagingModel

<h3>Results:</h3>
<table class="table table-bordered table-hover" id="ResultsTable">
    <thead>
        <tr>
            <td>ID</td>
            <td>NAME</td>
            <td>GENDER</td>
            <td>BIRTHPLACE</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Results)
        {
            <tr>
                <td>
                    @item.id
                </td>
                <td>
                    @item.name
                </td>
                <td>
                    @item.gender
                </td>
                <td>
                    @item.place_name
                </td>
            </tr>
        }
    </tbody>
</table>


@if (Model.NumberOfPages > 0)
{
    <nav aria-label="Page navigation">
        <ul class="pagination">
            @if (Model.CurrentPageNumber > 0)
            {
                <li>
                    <a href="javascript:;" class="changepage" aria-label="First" data-pagenumber="0">
                        <span aria-hidden="true">&laquo; First</span>
                    </a>
                </li>
                <li>
                    <a href="javascript:;" class="changepage" aria-label="Previous" data-pagenumber="@(Model.CurrentPageNumber - 1)">
                        <span aria-hidden="true">Previous</span>
                    </a>
                </li>
            }
            <!-- This is simplified due to time constraints -->
            <li class="active"><a href="javascript:;">Page: @(Model.CurrentPageNumber + 1) of @Model.NumberOfPages</a></li>

            @if (Model.CurrentPageNumber < (Model.NumberOfPages - 1))
            {
                <li>
                    <a href="javascript:;" class="changepage" aria-label="Next" data-pagenumber="@(Model.CurrentPageNumber + 1)">
                        <span aria-hidden="true">Next</span>
                    </a>
                </li>

                <li>
                    <a href="javascript:;" class="changepage" aria-label="Last" data-pagenumber="@(Model.NumberOfPages - 1)">
                        <span aria-hidden="true">Last &raquo;</span>
                    </a>
                </li>
            }

        </ul>
    </nav>
}

Deepend.DeependAncestry.Web/Views/Shared/_SearchForm.cshtml
@model Deepend.DeependAncestry.Web.Models.SearchFormModel

<form name="SearchForm" id="SearchForm" class="form-inline">
    <div class="col-md-7">
        <div class="col-md-12">
            @Html.TextBoxFor(model => model.name, new { placeholder = "Name", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.name)
        </div>
        <div class="col-md-12">
            <label>Gender: </label>
            <label class="checkbox-inline">
                @Html.CheckBoxFor(model => model.M) Male
            </label>
            <label class="checkbox-inline">
                @Html.CheckBoxFor(model => model.F) Female
            </label>

        </div>
    </div>
    <div class="col-md-5 text-center">
        <button id="btnSearch" type="submit" class="btn btn-primary" style="width: 100%;">Search</button>
        @Html.ActionLink("Advanced Search", "Index", "Advanced", null, new { @class = "advanced-search" })
    </div>

</form>